version: '3'

volumes:
  geo-db-data:
  geoserver-data:

services:
  db:
    container_name: "db"
    image: kartoza/postgis:13.0
    volumes:
      - geo-db-data:/var/lib/postgresql
      - ./postgis:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 5s
      retries: 3

  geoserver:
    container_name: "geoserver"
    image: kartoza/geoserver:2.19.0
    volumes:
      - ./geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - .env
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
