kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: BRANCH
    required: true
  - name: APP
    required: true
    value: geoserver
  - name: DB
    required: true
    value: postgis
  - name: DB_IMAGE
    required: true
    value: postgis/postgis:16-master
  - name: DB_HEALTHCHECK
    required: true
    value: '[
      "sh",
      "-c",
      "PGPASSWORD=$POSTGRES_PASSWORD
        psql -h 0.0.0.0 -U $POSTGRES_USER -d $POSTGRES_DATABASE -c \"SELECT 1\""
    ]'
  - name: DB_PATH
    required: true
    value: /var/lib/postgresql/data
  - name: DB_DATA
    required: true
    value: /pgdata
  - name: DB_PORT
    required: true
  - name: DB_USER
    required: true
  - name: DB_PASSWORD
    required: true
metadata:
  name: ${APP}
objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
   name: ${DB}-${BRANCH}
  spec:
    storageClassName: "standard-csi"
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: "10Gi"
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: ${DB}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${APP}
    template:
      metadata:
        labels:
          app: ${APP}
      spec:
        containers:
        - image: ${DB_IMAGE}
          name: ${DB}-${BRANCH}
          volumeMounts:
          - mountPath: ${DB_DATA}
            name: ${DB}-${BRANCH}
          ports:
            - containerPort: ${{DB_PORT}}
          livenessProbe:
            exec:
              command: ${{DB_HEALTHCHECK}}
            failureThreshold: 5
            periodSeconds: 30
          readinessProbe:
            exec:
              command: ${{DB_HEALTHCHECK}}
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
          - name: POSTGRES_DATABASE
            value: ${DB}
          - name: POSTGRES_USER
            value: ${DB_USER}
          - name: POSTGRES_PASSWORD
            value: ${DB_PASSWORD}
          - name: PGDATA
            value: ${DB_PATH}${DB_DATA}
        volumes:
        - name: ${DB}-${BRANCH}
          persistentVolumeClaim:
            claimName: ${DB}-${BRANCH}
