apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgis
  labels:
    io.kompose.service: postgis
spec:
  replicas: 1
  selector:
    io.kompose.service: postgis
  strategy:
    resources: { }
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgis
    spec:
      containers:
        - name: postgis
          image: registry.connect.redhat.com/crunchydata/crunchy-postgres-gis
          env:
            - name: PGBACKREST
              value: "true"
            - name: PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: PG_DATABASE
                  name: env
            - name: PG_PRIMARY_PORT
              valueFrom:
                configMapKeyRef:
                  key: PG_PORT
                  name: env
            - name: MODE
              value: postgres
            - name: PG_MODE
              valueFrom:
                configMapKeyRef:
                  key: PG_MODE
                  name: env
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  key: PG_USER
                  name: env
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: PG_PASSWORD
                  name: env
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PG_PASSWORD
                  name: env
            - name: PG_PRIMARY_USER
              valueFrom:
                configMapKeyRef:
                  key: PG_PRIMARY_USER
                  name: env
            - name: PG_PRIMARY_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PG_PRIMARY_PASSWORD
                  name: env
            - name: PG_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PG_ROOT_PASSWORD
                  name: env
          volumeMounts:
            - mountPath: /backrestrepo
              name: backrestrepo
            - mountPath: /backup
              name: backup
            - mountPath: /pgconf
              name: pgconf
            - mountPath: /pgdata
              name: pgdata
            - mountPath: /recover
              name: recover
          resources:
            requests:
              cpu: "0.25"
              memory: 1Gi
            limits:
              cpu: "0.5"
              memory: 2.5Gi
      volumes:
        - name: backrestrepo
          persistentVolumeClaim:
            claimName: backrestrepo
        - name: backup
          persistentVolumeClaim:
            claimName: backup
        - name: pgconf
          persistentVolumeClaim:
            claimName: pgconf
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
        - name: recover
          persistentVolumeClaim:
            claimName: recover
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - postgis
        from:
          kind: ImageStreamTag
          name: postgis:latest
      type: ImageChange
